
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-k8s-admin'
      routes: []
    receivers:
    - name: 'email-k8s-admin'
      email_configs:
      - to: '$receiver'
        from: 'email-k8s-admin@alertmanager.com'
        smarthost: '$smtp_host'
        auth_username: '$smtp_suer'
        auth_password: '$smtp_pass'
        auth_identity: '$email'
        send_resolved: true

